services:
  db:
    image: postgres:15
    container_name: counter_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: counter_test_db
    ports:
      - "5435:5432"